version: '3.9'

services:
  terraform:
    container_name: terraform
    entrypoint: ash
    image: hashicorp/terraform:latest
    working_dir: /tmp/
    volumes:
      - ./terraform/prod/:/tmp/terraform/
      - ./bigquery/:/tmp/bigquery/
      - ./Dockerfile.prod:/tmp/Dockerfile/
      - ./digdag/server.properties:/tmp/server.properties/
      - ~/.config/gcloud:/root/.config/gcloud
    env_file:
      ./secret/.env.prod
    tty: true
    secrets:
      - gcp_secret
  gcloud:
    container_name: "gcloud"
    entrypoint: "gcloud"
    image: google/cloud-sdk:alpine
    working_dir: /tmp/project
    volumes:
      - ./:/tmp/project:cached
      - gcloud-config:/root/.config
volumes:
  gcloud-config:
secrets:
  gcp_secret:
    file:
      ./secret/develop-test-k8s-asasaki.json