version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:11.1
    ports:
      - "5432:5432"
    volumes:
     - data:/var/lib/postgresql/data
    command: 
     - postgres
     - -c
     - superuser_reserved_connections=30
     - -c
     - max_connections=1000
    env_file:
      ./secret/.env
  digdag:
    container_name: digdag
    build:
      context: .
      args:
        DB_USER: postgresuser
        DB_PASSWORD: password
        DB_HOST: 0.0.0.0
        DB_PORT: 5432
        DB_NAME: digdag
        DIGDAG_ENCRYPTION_KEY: MdOyMzQ1NJc0oTAxMjM0PE==
    ports:
      - "65432:65432"
      - "65433:65433"
    volumes:
      - "./digdag/data:/var/data"
      - "./bigquery:/var/bigquery"
    working_dir: /var/data/
    tty: true
    depends_on:
      - postgres
    secrets:
      - gcp_secret
    env_file:
      ./secret/.env
  terraform:
    container_name: terraform
    entrypoint: ash
    image: hashicorp/terraform:latest
    working_dir: /tmp/terraform/
    volumes:
      - ./terraform/dev/:/tmp/terraform/
      - ./bigquery/:/tmp/bigquery/
    env_file:
      ./secret/.env
    tty: true
    secrets:
      - gcp_secret
  gcloud:
    container_name: "gcloud"
    entrypoint: "gcloud"
    image: google/cloud-sdk:alpine
    working_dir: /tmp/project
    volumes:
      - ./:/tmp/project:cached
      - gcloud-config:/root/.config
volumes:
  gcloud-config:
  data:
secrets:
  gcp_secret:
    file:
      ./secret/develop-test-k8s-asasaki.json