version: '3.9'

services:
  postgresql:
    container_name: postgres
    image: postgres:11.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digdag
    command: 
     - postgres
     - -c
     - superuser_reserved_connections=30
     - -c
     - max_connections=1000
  digdag:
    container_name: digdag
    build:
      context: .
      args:
        DB_USER: postgresuser
        DB_PASSWORD: password
        DB_HOST: postgresql
        DB_PORT: 5432
        DB_NAME: digdag
        DIGDAG_ENCRYPTION_KEY: MdOyMzQ1NJc0oTAxMjM0PE==
    ports:
      - "65432:65432"
      - "65433:65433"
    volumes:
      - "./digdag/data:/var/data"
      - "./bigquery:/var/bigquery"
    tty: true
    depends_on:
      - postgresql
    secrets:
      - gcp_secret
    env_file:
      ./secret/.env
  terraform:
    container_name: terraform
    entrypoint: ash
    image: hashicorp/terraform:latest
    working_dir: /tmp/terraform/
    volumes:
      - ./terraform/:/tmp/terraform/
      - ./bigquery/:/tmp/bigquery/
    env_file:
      ./secret/.env
    tty: true
    secrets:
      - gcp_secret
  gcloud:
    container_name: "gcloud"
    entrypoint: "gcloud"
    image: google/cloud-sdk:alpine
    working_dir: /tmp/project
    volumes:
      - ./:/tmp/project:cached
      - gcloud-config:/root/.config
volumes:
  gcloud-config:
secrets:
  gcp_secret:
    file:
      ./secret/develop-test-k8s-asasaki.json