version: '3.9'

services:
  terraform:
    container_name: terraform_prod
    entrypoint: ash
    image: hashicorp/terraform:latest
    working_dir: /tmp
    volumes:
      - ../terraform/prod/:/tmp/terraform/
      - ../bigquery/:/tmp/bigquery/
      - gcloud-config:/root/.config
    env_file:
      ../secret/.env.prod
    tty: true
    secrets:
      - gcp_secret
  gcloud:
    container_name: gcloud_prod
    entrypoint: "gcloud"
    image: google/cloud-sdk:alpine
    working_dir: /tmp
    volumes:
      - ../:/tmp:cached
      - gcloud-config:/root/.config
    tty: true
volumes:
  gcloud-config:
secrets:
  gcp_secret:
    file:
      ../secret/develop-test-k8s-asasaki.json